# Assemble the built R packages from the parameterized synapser build. 
# Zip them into a zipped tarball based on the R version with which they were built. 

# this will be the name of the archive containing all
# the built R packages. click on the link below for
# a description of the available environment variables
ARCHNAME=${JOB_NAME}_${BUILD_NUMBER}.zip

# create the output directories. strip of the "RVERS;" part of the directory
# name that is generated by the parameterized build plugin. See the docs
# for that plugin for additional details.
ls | grep RVERS | sed 's/^RVERS=//;s/,.*$//g' | uniq | awk '{print("mkdir -p " $1)}' | sh

# copy the build artifacts based on R version
for vers in `ls | grep RVERS | sed 's/^RVERS=//;s/,.*$//g' | uniq`
do
  for dir in `ls | grep "RVERS=$vers"`
  do
    for file in `ls $dir/*`
    do
    
      file_version=`echo ${file%.*} | awk -F'[_]' '{print $2}' | sed 's/.tar//g'`
      if [ -z ${VERSION} ]
      then
      	export VERSION=$file_version
      else
      	if [ "$VERSION" != "$file_version" ]
        then
          echo "artifacts have different version"
          exit 1
        fi
      fi
      
      echo file $file vers $vers
      cp $file $vers
    done
  done
  # add to archive file
  zip -r $ARCHNAME $vers
done
